import type { LonLatBox } from '../../../assets/data/travel'

/**
 * Detail geometry, sliced to 50m by `npm run geo` and fetched when a country
 * opens rather than bundled: all twelve come to ~384 KB against a 130 KB page
 * chunk, and you only ever look at one.
 */
const cache = new Map<string, Promise<unknown>>()

const loadJson = <T,>(url: string): Promise<T> => {
  const hit = cache.get(url)
  if (hit) return hit as Promise<T>

  const request = fetch(url)
    .then(response => {
      if (!response.ok) throw new Error(`No geometry at ${url}`)
      return response.json() as Promise<T>
    })
    // A rejected promise would otherwise sit in the cache forever, so one
    // dropped request would break that country for the rest of the session.
    .catch(error => {
      cache.delete(url)
      throw error
    })

  cache.set(url, request)
  return request
}

export const loadCountry = (id: string) =>
  loadJson<GeoJSON.Feature>(`/geo/countries/${id}.json`)

/** A subdivision layer, e.g. 'us-states'. Generated by `npm run geo`. */
export const loadRegions = (source: string) =>
  loadJson<GeoJSON.FeatureCollection>(`/geo/${source}.json`)

/** Every vertex of the ring sits inside the lon/lat box. */
export const insideBox = (ring: GeoJSON.Position[], box: LonLatBox) => {
  const [minLon, minLat, maxLon, maxLat] = box
  return ring.every(
    ([lon, lat]) =>
      lon >= minLon && lon <= maxLon && lat >= minLat && lat <= maxLat
  )
}

/**
 * Drops the sub-polygons that fall outside the box. The detail view fits its
 * projection to whatever it is handed, so leaving French Guiana in would shrink
 * metropolitan France to a speck in the corner.
 */
export const restrictToBox = (
  geometry: GeoJSON.Geometry,
  box: LonLatBox | undefined
): GeoJSON.Geometry => {
  if (!box || geometry.type !== 'MultiPolygon') return geometry
  const kept = geometry.coordinates.filter(polygon => insideBox(polygon[0], box))
  return kept.length ? { type: 'MultiPolygon', coordinates: kept } : geometry
}
